### PR TITLE
Add selectable map regions

### LINKED ISSUE #51: Update heatmap for cases by region at the woreda level and restrict map to Ethiopia.
Needs: 
Geographic overlay data for each woreda/admin region
Number of cases by region
Number tested by region*

*If we can get access to this data

### PR DESCRIPTION
**Pull request by yohannesHL**
Closes #51  
@helomberhane @yohane55 

Updated map (as i had already started working on it :smiley: )
Add support for `onRegionClick` and `onRegionHover` events for other charts to hook on
This is still using leaflet and openstreet maps ( so no need for API licences).

### CODE REVIEW

**Comment by yohannesHL** [comment]
localhost_8000_

**Comment by helomberhane** [comment]
I would hold on merging this in, we'll need to coordinate how/where to fit this into the current layout.

**Comment by yohane55** [comment]
@yohannesHL and @helomberhane  you both did good on the map!! @helomberhane is there any update on Gmap api free credit?

I think it is good to have both regional and zonal geojson and case/medical facility data.

**Comment by yohannesHL** [comment]
@helomberhane @yohane55 Think i misunderstood and thought that we only needed admin regions not woredas. But it should be possible to show woredas on the region via click handler (similar to https://ws456999.github.io/vue-echarts-map-drill-down/#/). Currently it zooms in to the region but we can render the woreda overlay too.

**Comment by yohane55** [comment]
In my opinion that seems the right approach for showinh number of cases, but for health facilities we still can use the woreda/zonal geojeson.

**Comment by yohane55** [comment]
@helomberhane can we continue working on leaflet? can you re-do your changes on leaflet??

**Comment by yohannesHL** [comment]
@helomberhane  Can you have a look

**Pull request closed without merging**
